#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the shmn network
 * AUTOGENERATED by share/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
       {{0x26,0x04,0x68,0x00,0x5e,0x11,0x36,0x11,0x00,0x00,0x00,0x01}, 50005}, // 2604:6800:5e11:3611:0000:0001
	{{0x26,0x04,0x68,0x00,0x5e,0x11,0x36,0x11,0x00,0x00,0x00,0x02}, 50005}, // 2604:6800:5e11:3611:0000:0002
    };
static SeedSpec6 pnSeed6_test[] = {
    };
#endif // BITCOIN_CHAINPARAMSSEEDS_H
